package com.healthcare.system.HealthcareAPI.service;

import com.healthcare.system.HealthcareAPI.entity.Doctors;
import com.healthcare.system.HealthcareAPI.repository.DoctorsRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;


/**
 * Service class for Doctors entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class DoctorsService {

    private final DoctorsRepository repository;

    public DoctorsService(DoctorsRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Doctors
     */
    public Doctors create(Doctors entity) {
        return repository.save(entity);
    }

    /**
     * Find Doctors by ID
     */
    public Optional<Doctors> findById(Integer id) {
        return repository.findById(id);
    }

    /**
     * Get all Doctors entities
     */
    public List<Doctors> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Doctors
     */
    public Doctors update(Integer id, Doctors entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Doctors not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Doctors by ID
     */
    public void delete(Integer id) {
        repository.deleteById(id);
    }

    /**
     * Check if Doctors exists by ID
     */
    public boolean exists(Integer id) {
        return repository.existsById(id);
    }
}
