package com.healthcare.system.HealthcareAPI.service;

import com.healthcare.system.HealthcareAPI.entity.MedicalSpecialties;
import com.healthcare.system.HealthcareAPI.repository.MedicalSpecialtiesRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;


/**
 * Service class for MedicalSpecialties entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class MedicalSpecialtiesService {

    private final MedicalSpecialtiesRepository repository;

    public MedicalSpecialtiesService(MedicalSpecialtiesRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new MedicalSpecialties
     */
    public MedicalSpecialties create(MedicalSpecialties entity) {
        return repository.save(entity);
    }

    /**
     * Find MedicalSpecialties by ID
     */
    public Optional<MedicalSpecialties> findById(Integer id) {
        return repository.findById(id);
    }

    /**
     * Get all MedicalSpecialties entities
     */
    public List<MedicalSpecialties> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing MedicalSpecialties
     */
    public MedicalSpecialties update(Integer id, MedicalSpecialties entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("MedicalSpecialties not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete MedicalSpecialties by ID
     */
    public void delete(Integer id) {
        repository.deleteById(id);
    }

    /**
     * Check if MedicalSpecialties exists by ID
     */
    public boolean exists(Integer id) {
        return repository.existsById(id);
    }
}
