package com.healthcare.system.HealthcareAPI.service;

import com.healthcare.system.HealthcareAPI.entity.Patients;
import com.healthcare.system.HealthcareAPI.repository.PatientsRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;


/**
 * Service class for Patients entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class PatientsService {

    private final PatientsRepository repository;

    public PatientsService(PatientsRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Patients
     */
    public Patients create(Patients entity) {
        return repository.save(entity);
    }

    /**
     * Find Patients by ID
     */
    public Optional<Patients> findById(Integer id) {
        return repository.findById(id);
    }

    /**
     * Get all Patients entities
     */
    public List<Patients> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Patients
     */
    public Patients update(Integer id, Patients entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Patients not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Patients by ID
     */
    public void delete(Integer id) {
        repository.deleteById(id);
    }

    /**
     * Check if Patients exists by ID
     */
    public boolean exists(Integer id) {
        return repository.existsById(id);
    }
}
