package com.healthcare.system.HealthcareAPI.service;

import com.healthcare.system.HealthcareAPI.entity.Prescriptions;
import com.healthcare.system.HealthcareAPI.repository.PrescriptionsRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;


/**
 * Service class for Prescriptions entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class PrescriptionsService {

    private final PrescriptionsRepository repository;

    public PrescriptionsService(PrescriptionsRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Prescriptions
     */
    public Prescriptions create(Prescriptions entity) {
        return repository.save(entity);
    }

    /**
     * Find Prescriptions by ID
     */
    public Optional<Prescriptions> findById(Integer id) {
        return repository.findById(id);
    }

    /**
     * Get all Prescriptions entities
     */
    public List<Prescriptions> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Prescriptions
     */
    public Prescriptions update(Integer id, Prescriptions entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Prescriptions not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Prescriptions by ID
     */
    public void delete(Integer id) {
        repository.deleteById(id);
    }

    /**
     * Check if Prescriptions exists by ID
     */
    public boolean exists(Integer id) {
        return repository.existsById(id);
    }
}
