package com.test.TestManyToMany.repository;

import com.test.TestManyToMany.entity.Course;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * Repository interface for Course entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface CourseRepository extends JpaRepository<Course, Long> {
    
    // Custom query methods can be added here
    
}
