package com.test.TestManyToMany.repository;

import com.test.TestManyToMany.entity.Student;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * Repository interface for Student entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface StudentRepository extends JpaRepository<Student, Long> {
    
    // Custom query methods can be added here
    
}
