version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: HealthcareAPI-db
    environment:
      POSTGRES_DB: healthcare_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - HealthcareAPI-network

volumes:
  postgres_data:

networks:
  HealthcareAPI-network:
    driver: bridge
