package com.mde.test.FullSystem.service;

import com.mde.test.FullSystem.entity.Category;
import com.mde.test.FullSystem.repository.CategoryRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;


/**
 * Service class for Category entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class CategoryService {

    private final CategoryRepository repository;

    public CategoryService(CategoryRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Category
     */
    public Category create(Category entity) {
        return repository.save(entity);
    }

    /**
     * Find Category by ID
     */
    public Optional<Category> findById(Long id) {
        return repository.findById(id);
    }

    /**
     * Get all Category entities
     */
    public List<Category> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Category
     */
    public Category update(Long id, Category entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Category not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Category by ID
     */
    public void delete(Long id) {
        repository.deleteById(id);
    }

    /**
     * Check if Category exists by ID
     */
    public boolean exists(Long id) {
        return repository.existsById(id);
    }
}
