package com.mde.test.FullSystem.service;

import com.mde.test.FullSystem.entity.Post;
import com.mde.test.FullSystem.repository.PostRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;


/**
 * Service class for Post entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class PostService {

    private final PostRepository repository;

    public PostService(PostRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Post
     */
    public Post create(Post entity) {
        return repository.save(entity);
    }

    /**
     * Find Post by ID
     */
    public Optional<Post> findById(Long id) {
        return repository.findById(id);
    }

    /**
     * Get all Post entities
     */
    public List<Post> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Post
     */
    public Post update(Long id, Post entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Post not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Post by ID
     */
    public void delete(Long id) {
        repository.deleteById(id);
    }

    /**
     * Check if Post exists by ID
     */
    public boolean exists(Long id) {
        return repository.existsById(id);
    }
}
