package com.mde.test.FullSystem.service;

import com.mde.test.FullSystem.entity.Profile;
import com.mde.test.FullSystem.repository.ProfileRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;


/**
 * Service class for Profile entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class ProfileService {

    private final ProfileRepository repository;

    public ProfileService(ProfileRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Profile
     */
    public Profile create(Profile entity) {
        return repository.save(entity);
    }

    /**
     * Find Profile by ID
     */
    public Optional<Profile> findById(Long id) {
        return repository.findById(id);
    }

    /**
     * Get all Profile entities
     */
    public List<Profile> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Profile
     */
    public Profile update(Long id, Profile entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Profile not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Profile by ID
     */
    public void delete(Long id) {
        repository.deleteById(id);
    }

    /**
     * Check if Profile exists by ID
     */
    public boolean exists(Long id) {
        return repository.existsById(id);
    }
}
