package com.healthcare.system.HealthcareAPI.repository;

import com.healthcare.system.HealthcareAPI.entity.Appointments;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * Repository interface for Appointments entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface AppointmentsRepository extends JpaRepository<Appointments, Integer> {
    
    // Custom query methods can be added here
    
}
