package com.healthcare.system.HealthcareAPI.repository;

import com.healthcare.system.HealthcareAPI.entity.Doctors;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * Repository interface for Doctors entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface DoctorsRepository extends JpaRepository<Doctors, Integer> {
    
    // Custom query methods can be added here
    
}
