package com.healthcare.system.HealthcareAPI.repository;

import com.healthcare.system.HealthcareAPI.entity.MedicalSpecialties;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * Repository interface for MedicalSpecialties entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface MedicalSpecialtiesRepository extends JpaRepository<MedicalSpecialties, Integer> {
    
    // Custom query methods can be added here
    
}
