package com.healthcare.system.HealthcareAPI.repository;

import com.healthcare.system.HealthcareAPI.entity.MedicalRecords;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * Repository interface for MedicalRecords entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface MedicalRecordsRepository extends JpaRepository<MedicalRecords, Integer> {
    
    // Custom query methods can be added here
    
}
