package com.healthcare.system.HealthcareAPI.repository;

import com.healthcare.system.HealthcareAPI.entity.Patients;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * Repository interface for Patients entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface PatientsRepository extends JpaRepository<Patients, Integer> {
    
    // Custom query methods can be added here
    
}
