package com.healthcare.system.HealthcareAPI.repository;

import com.healthcare.system.HealthcareAPI.entity.Prescriptions;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * Repository interface for Prescriptions entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface PrescriptionsRepository extends JpaRepository<Prescriptions, Integer> {
    
    // Custom query methods can be added here
    
}
