package com.mde.test.FullSystem.repository;

import com.mde.test.FullSystem.entity.Category;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * Repository interface for Category entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface CategoryRepository extends JpaRepository<Category, Long> {
    
    // Custom query methods can be added here
    
}
