package com.mde.test.FullSystem.repository;

import com.mde.test.FullSystem.entity.Post;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * Repository interface for Post entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface PostRepository extends JpaRepository<Post, Long> {
    
    // Custom query methods can be added here
    
}
