package com.mde.test.FullSystem.repository;

import com.mde.test.FullSystem.entity.Profile;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * Repository interface for Profile entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface ProfileRepository extends JpaRepository<Profile, Long> {
    
    // Custom query methods can be added here
    
}
