package com.mde.test.FullSystem.repository;

import com.mde.test.FullSystem.entity.Users;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * Repository interface for Users entity
 * Generated by MDE Backend Generator
 */
@Repository
public interface UsersRepository extends JpaRepository<Users, Long> {
    
    // Custom query methods can be added here
    
}
