package com.healthcare.system.HealthcareAPI.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;

/**
 * JPA Auditing Configuration
 * Enables automatic population of @CreatedDate and @LastModifiedDate fields
 * Generated by MDE Backend Generator
 */
@Configuration
@EnableJpaAuditing
public class JpaAuditingConfig {
    // Enables JPA auditing for automatic timestamp management
}
