package com.healthcare.system.HealthcareAPI.controller;

import com.healthcare.system.HealthcareAPI.entity.Appointments;
import com.healthcare.system.HealthcareAPI.service.AppointmentsService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;


/**
 * REST Controller for Appointments entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/appointments")
@CrossOrigin(origins = "*")
public class AppointmentsController {

    private final AppointmentsService service;

    public AppointmentsController(AppointmentsService service) {
        this.service = service;
    }

    /**
     * Create a new Appointments
     * POST /api/appointments
     */
    @PostMapping
    public ResponseEntity<Appointments> create(@RequestBody Appointments entity) {
        Appointments created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get Appointments by ID
     * GET /api/appointments/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<Appointments> getById(@PathVariable Integer id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all Appointments entities
     * GET /api/appointments
     */
    @GetMapping
    public ResponseEntity<List<Appointments>> getAll() {
        List<Appointments> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing Appointments
     * PUT /api/appointments/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<Appointments> update(
            @PathVariable Integer id,
            @RequestBody Appointments entity) {
        try {
            Appointments updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete Appointments by ID
     * DELETE /api/appointments/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Integer id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
