package com.healthcare.system.HealthcareAPI.controller;

import com.healthcare.system.HealthcareAPI.entity.MedicalSpecialties;
import com.healthcare.system.HealthcareAPI.service.MedicalSpecialtiesService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;


/**
 * REST Controller for MedicalSpecialties entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/medical_specialties")
@CrossOrigin(origins = "*")
public class MedicalSpecialtiesController {

    private final MedicalSpecialtiesService service;

    public MedicalSpecialtiesController(MedicalSpecialtiesService service) {
        this.service = service;
    }

    /**
     * Create a new MedicalSpecialties
     * POST /api/medical_specialties
     */
    @PostMapping
    public ResponseEntity<MedicalSpecialties> create(@RequestBody MedicalSpecialties entity) {
        MedicalSpecialties created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get MedicalSpecialties by ID
     * GET /api/medical_specialties/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<MedicalSpecialties> getById(@PathVariable Integer id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all MedicalSpecialties entities
     * GET /api/medical_specialties
     */
    @GetMapping
    public ResponseEntity<List<MedicalSpecialties>> getAll() {
        List<MedicalSpecialties> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing MedicalSpecialties
     * PUT /api/medical_specialties/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<MedicalSpecialties> update(
            @PathVariable Integer id,
            @RequestBody MedicalSpecialties entity) {
        try {
            MedicalSpecialties updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete MedicalSpecialties by ID
     * DELETE /api/medical_specialties/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Integer id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
