package com.healthcare.system.HealthcareAPI.controller;

import com.healthcare.system.HealthcareAPI.entity.MedicalRecords;
import com.healthcare.system.HealthcareAPI.service.MedicalRecordsService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;


/**
 * REST Controller for MedicalRecords entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/medical_records")
@CrossOrigin(origins = "*")
public class MedicalRecordsController {

    private final MedicalRecordsService service;

    public MedicalRecordsController(MedicalRecordsService service) {
        this.service = service;
    }

    /**
     * Create a new MedicalRecords
     * POST /api/medical_records
     */
    @PostMapping
    public ResponseEntity<MedicalRecords> create(@RequestBody MedicalRecords entity) {
        MedicalRecords created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get MedicalRecords by ID
     * GET /api/medical_records/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<MedicalRecords> getById(@PathVariable Integer id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all MedicalRecords entities
     * GET /api/medical_records
     */
    @GetMapping
    public ResponseEntity<List<MedicalRecords>> getAll() {
        List<MedicalRecords> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing MedicalRecords
     * PUT /api/medical_records/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<MedicalRecords> update(
            @PathVariable Integer id,
            @RequestBody MedicalRecords entity) {
        try {
            MedicalRecords updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete MedicalRecords by ID
     * DELETE /api/medical_records/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Integer id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
