package com.healthcare.system.HealthcareAPI.controller;

import com.healthcare.system.HealthcareAPI.entity.Patients;
import com.healthcare.system.HealthcareAPI.service.PatientsService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;


/**
 * REST Controller for Patients entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/patients")
@CrossOrigin(origins = "*")
public class PatientsController {

    private final PatientsService service;

    public PatientsController(PatientsService service) {
        this.service = service;
    }

    /**
     * Create a new Patients
     * POST /api/patients
     */
    @PostMapping
    public ResponseEntity<Patients> create(@RequestBody Patients entity) {
        Patients created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get Patients by ID
     * GET /api/patients/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<Patients> getById(@PathVariable Integer id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all Patients entities
     * GET /api/patients
     */
    @GetMapping
    public ResponseEntity<List<Patients>> getAll() {
        List<Patients> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing Patients
     * PUT /api/patients/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<Patients> update(
            @PathVariable Integer id,
            @RequestBody Patients entity) {
        try {
            Patients updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete Patients by ID
     * DELETE /api/patients/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Integer id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
