package com.test.TestManyToMany.service;

import com.test.TestManyToMany.entity.Course;
import com.test.TestManyToMany.repository.CourseRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;


/**
 * Service class for Course entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class CourseService {

    private final CourseRepository repository;

    public CourseService(CourseRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Course
     */
    public Course create(Course entity) {
        return repository.save(entity);
    }

    /**
     * Find Course by ID
     */
    public Optional<Course> findById(Long id) {
        return repository.findById(id);
    }

    /**
     * Get all Course entities
     */
    public List<Course> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Course
     */
    public Course update(Long id, Course entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Course not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Course by ID
     */
    public void delete(Long id) {
        repository.deleteById(id);
    }

    /**
     * Check if Course exists by ID
     */
    public boolean exists(Long id) {
        return repository.existsById(id);
    }
}
