package com.test.TestManyToMany.service;

import com.test.TestManyToMany.entity.Student;
import com.test.TestManyToMany.repository.StudentRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;


/**
 * Service class for Student entity
 * Generated by MDE Backend Generator
 */
@Service
@Transactional
public class StudentService {

    private final StudentRepository repository;

    public StudentService(StudentRepository repository) {
        this.repository = repository;
    }

    /**
     * Create a new Student
     */
    public Student create(Student entity) {
        return repository.save(entity);
    }

    /**
     * Find Student by ID
     */
    public Optional<Student> findById(Long id) {
        return repository.findById(id);
    }

    /**
     * Get all Student entities
     */
    public List<Student> findAll() {
        return repository.findAll();
    }

    /**
     * Update an existing Student
     */
    public Student update(Long id, Student entity) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Student not found with id: " + id);
        }
        entity.setId(id);
        return repository.save(entity);
    }

    /**
     * Delete Student by ID
     */
    public void delete(Long id) {
        repository.deleteById(id);
    }

    /**
     * Check if Student exists by ID
     */
    public boolean exists(Long id) {
        return repository.existsById(id);
    }
}
