package com.mde.test.FullSystem.controller;

import com.mde.test.FullSystem.entity.Post;
import com.mde.test.FullSystem.service.PostService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;


/**
 * REST Controller for Post entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/post")
@CrossOrigin(origins = "*")
public class PostController {

    private final PostService service;

    public PostController(PostService service) {
        this.service = service;
    }

    /**
     * Create a new Post
     * POST /api/post
     */
    @PostMapping
    public ResponseEntity<Post> create(@RequestBody Post entity) {
        Post created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get Post by ID
     * GET /api/post/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<Post> getById(@PathVariable Long id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all Post entities
     * GET /api/post
     */
    @GetMapping
    public ResponseEntity<List<Post>> getAll() {
        List<Post> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing Post
     * PUT /api/post/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<Post> update(
            @PathVariable Long id,
            @RequestBody Post entity) {
        try {
            Post updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete Post by ID
     * DELETE /api/post/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
