package com.mde.test.FullSystem.controller;

import com.mde.test.FullSystem.entity.Profile;
import com.mde.test.FullSystem.service.ProfileService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;


/**
 * REST Controller for Profile entity
 * Generated by MDE Backend Generator
 */
@RestController
@RequestMapping("/api/profile")
@CrossOrigin(origins = "*")
public class ProfileController {

    private final ProfileService service;

    public ProfileController(ProfileService service) {
        this.service = service;
    }

    /**
     * Create a new Profile
     * POST /api/profile
     */
    @PostMapping
    public ResponseEntity<Profile> create(@RequestBody Profile entity) {
        Profile created = service.create(entity);
        return new ResponseEntity<>(created, HttpStatus.CREATED);
    }

    /**
     * Get Profile by ID
     * GET /api/profile/{id}
     */
    @GetMapping("/{id}")
    public ResponseEntity<Profile> getById(@PathVariable Long id) {
        return service.findById(id)
                .map(entity -> new ResponseEntity<>(entity, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Get all Profile entities
     * GET /api/profile
     */
    @GetMapping
    public ResponseEntity<List<Profile>> getAll() {
        List<Profile> entities = service.findAll();
        return new ResponseEntity<>(entities, HttpStatus.OK);
    }

    /**
     * Update an existing Profile
     * PUT /api/profile/{id}
     */
    @PutMapping("/{id}")
    public ResponseEntity<Profile> update(
            @PathVariable Long id,
            @RequestBody Profile entity) {
        try {
            Profile updated = service.update(id, entity);
            return new ResponseEntity<>(updated, HttpStatus.OK);
        } catch (RuntimeException e) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * Delete Profile by ID
     * DELETE /api/profile/{id}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        if (!service.exists(id)) {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        service.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}
