package com.healthcare.system.HealthcareAPI.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

/**
 * Entity class for appointments table
 * Generated by MDE Backend Generator
 */
@Entity
@Table(name = "appointments")
@EntityListeners(AuditingEntityListener.class)
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Appointments implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", nullable = false)
    private Integer id;
    
    @Column(name = "appointment_date", nullable = false)
    private LocalDateTime appointmentDate;
    
    @Column(name = "duration", nullable = true)
    private Integer duration;
    
    @Column(name = "status", nullable = true)
    private String status;
    
    @Column(name = "notes", nullable = true)
    private String notes;
    
    @CreatedDate
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
    
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")    private List<Patients> patient;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")    private List<Doctors> doctor;
    
}
