package com.healthcare.system.HealthcareAPI.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.LocalDate;
import java.util.List;
import java.util.Set;

/**
 * Entity class for medical_records table
 * Generated by MDE Backend Generator
 */
@Entity
@Table(name = "medical_records")
@EntityListeners(AuditingEntityListener.class)
@Data
@NoArgsConstructor
@AllArgsConstructor
public class MedicalRecords implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", nullable = false)
    private Integer id;
    
    @Column(name = "record_date", nullable = false)
    private LocalDateTime recordDate;
    
    @Column(name = "diagnosis", nullable = false)
    private String diagnosis;
    
    @Column(name = "symptoms", nullable = true)
    private String symptoms;
    
    @Column(name = "treatment", nullable = true)
    private String treatment;
    
    @Column(name = "follow_up_required", nullable = true)
    private Boolean followUpRequired;
    
    @Column(name = "follow_up_date", nullable = true)
    private LocalDate followUpDate;
    
    @CreatedDate
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
    
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")    private List<Patients> patient;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")    private List<Doctors> doctor;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "appointment")    private List<Appointments> appointment;
    
}
