package com.healthcare.system.HealthcareAPI.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.LocalDate;
import java.util.List;
import java.util.Set;

/**
 * Entity class for prescriptions table
 * Generated by MDE Backend Generator
 */
@Entity
@Table(name = "prescriptions")
@EntityListeners(AuditingEntityListener.class)
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Prescriptions implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", nullable = false)
    private Integer id;
    
    @Column(name = "medication_name", nullable = false)
    private String medicationName;
    
    @Column(name = "dosage", nullable = false)
    private String dosage;
    
    @Column(name = "frequency", nullable = false)
    private String frequency;
    
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;
    
    @Column(name = "end_date", nullable = true)
    private LocalDate endDate;
    
    @Column(name = "instructions", nullable = true)
    private String instructions;
    
    @Column(name = "refills_allowed", nullable = true)
    private Integer refillsAllowed;
    
    @Column(name = "is_active", nullable = true)
    private Boolean isActive;
    
    @CreatedDate
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
    
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")    private List<Patients> patient;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")    private List<Doctors> doctor;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "medical_record")    private List<MedicalRecords> medical_record;
    
}
